// Generated using https://www.html-code-generator.com/javascript/json/languages-name-and-code
// length 143

export interface Language {
  name: string;
  code: string;
  id: number;
}

export var languages_list : Language[] = [
  {"name":"Afrikaans","code":"af","id":1},
  {"name":"Albanian - shqip","code":"sq","id":2},
  {"name":"Amharic - አማርኛ","code":"am","id":3},
  {"name":"Arabic - العربية","code":"ar","id":4},
  {"name":"Aragonese - aragonés","code":"an","id":5},
  {"name":"Armenian - հայերեն","code":"hy","id":6},
  {"name":"Asturian - asturianu","code":"ast","id":7},
  {"name":"Azerbaijani - azərbaycan dili","code":"az","id":8},
  {"name":"Basque - euskara","code":"eu","id":9},
  {"name":"Belarusian - беларуская","code":"be","id":10},
  {"name":"Bengali - বাংলা","code":"bn","id":11},
  {"name":"Bosnian - bosanski","code":"bs","id":12},
  {"name":"Breton - brezhoneg","code":"br","id":13},
  {"name":"Bulgarian - български","code":"bg","id":14},
  {"name":"Catalan - català","code":"ca","id":15},
  {"name":"Central Kurdish - کوردی (دەستنوسی عەرەبی)","code":"ckb","id":16},
  {"name":"Chinese - 中文","code":"zh","id":17},
  {"name":"Chinese (Hong Kong) - 中文（香港）","code":"zh-HK","id":18},
  {"name":"Chinese (Simplified) - 中文（简体）","code":"zh-CN","id":19},
  {"name":"Chinese (Traditional) - 中文（繁體）","code":"zh-TW","id":20},
  {"name":"Corsican","code":"co","id":21},
  {"name":"Croatian - hrvatski","code":"hr","id":22},
  {"name":"Czech - čeština","code":"cs","id":23},
  {"name":"Danish - dansk","code":"da","id":24},
  {"name":"Dutch - Nederlands","code":"nl","id":25},
  {"name":"English","code":"en","id":26},
  {"name":"English (Australia)","code":"en-AU","id":27},
  {"name":"English (Canada)","code":"en-CA","id":28},
  {"name":"English (India)","code":"en-IN","id":29},
  {"name":"English (New Zealand)","code":"en-NZ","id":30},
  {"name":"English (South Africa)","code":"en-ZA","id":31},
  {"name":"English (United Kingdom)","code":"en-GB","id":32},
  {"name":"English (United States)","code":"en-US","id":33},
  {"name":"Esperanto - esperanto","code":"eo","id":34},
  {"name":"Estonian - eesti","code":"et","id":35},
  {"name":"Faroese - føroyskt","code":"fo","id":36},
  {"name":"Filipino","code":"fil","id":37},
  {"name":"Finnish - suomi","code":"fi","id":38},
  {"name":"French - français","code":"fr","id":39},
  {"name":"French (Canada) - français (Canada)","code":"fr-CA","id":40},
  {"name":"French (France) - français (France)","code":"fr-FR","id":41},
  {"name":"French (Switzerland) - français (Suisse)","code":"fr-CH","id":42},
  {"name":"Galician - galego","code":"gl","id":43},
  {"name":"Georgian - ქართული","code":"ka","id":44},
  {"name":"German - Deutsch","code":"de","id":45},
  {"name":"German (Austria) - Deutsch (Österreich)","code":"de-AT","id":46},
  {"name":"German (Germany) - Deutsch (Deutschland)","code":"de-DE","id":47},
  {"name":"German (Liechtenstein) - Deutsch (Liechtenstein)","code":"de-LI","id":48},
  {"name":"German (Switzerland) - Deutsch (Schweiz)","code":"de-CH","id":49},
  {"name":"Greek - Ελληνικά","code":"el","id":50},
  {"name":"Guarani","code":"gn","id":51},
  {"name":"Gujarati - ગુજરાતી","code":"gu","id":52},
  {"name":"Hausa","code":"ha","id":53},
  {"name":"Hawaiian - ʻŌlelo Hawaiʻi","code":"haw","id":54},
  {"name":"Hebrew - עברית","code":"he","id":55},
  {"name":"Hindi - हिन्दी","code":"hi","id":56},
  {"name":"Hungarian - magyar","code":"hu","id":57},
  {"name":"Icelandic - íslenska","code":"is","id":58},
  {"name":"Indonesian - Indonesia","code":"id","id":59},
  {"name":"Interlingua","code":"ia","id":60},
  {"name":"Irish - Gaeilge","code":"ga","id":61},
  {"name":"Italian - italiano","code":"it","id":62},
  {"name":"Italian (Italy) - italiano (Italia)","code":"it-IT","id":63},
  {"name":"Italian (Switzerland) - italiano (Svizzera)","code":"it-CH","id":64},
  {"name":"Japanese - 日本語","code":"ja","id":65},
  {"name":"Kannada - ಕನ್ನಡ","code":"kn","id":66},
  {"name":"Kazakh - қазақ тілі","code":"kk","id":67},
  {"name":"Khmer - ខ្មែរ","code":"km","id":68},
  {"name":"Korean - 한국어","code":"ko","id":69},
  {"name":"Kurdish - Kurdî","code":"ku","id":70},
  {"name":"Kyrgyz - кыргызча","code":"ky","id":71},
  {"name":"Lao - ລາວ","code":"lo","id":72},
  {"name":"Latin","code":"la","id":73},
  {"name":"Latvian - latviešu","code":"lv","id":74},
  {"name":"Lingala - lingála","code":"ln","id":75},
  {"name":"Lithuanian - lietuvių","code":"lt","id":76},
  {"name":"Macedonian - македонски","code":"mk","id":77},
  {"name":"Malay - Bahasa Melayu","code":"ms","id":78},
  {"name":"Malayalam - മലയാളം","code":"ml","id":79},
  {"name":"Maltese - Malti","code":"mt","id":80},
  {"name":"Marathi - मराठी","code":"mr","id":81},
  {"name":"Mongolian - монгол","code":"mn","id":82},
  {"name":"Nepali - नेपाली","code":"ne","id":83},
  {"name":"Norwegian - norsk","code":"no","id":84},
  {"name":"Norwegian Bokmål - norsk bokmål","code":"nb","id":85},
  {"name":"Norwegian Nynorsk - nynorsk","code":"nn","id":86},
  {"name":"Occitan","code":"oc","id":87},
  {"name":"Oriya - ଓଡ଼ିଆ","code":"or","id":88},
  {"name":"Oromo - Oromoo","code":"om","id":89},
  {"name":"Pashto - پښتو","code":"ps","id":90},
  {"name":"Persian - فارسی","code":"fa","id":91},
  {"name":"Polish - polski","code":"pl","id":92},
  {"name":"Portuguese - português","code":"pt","id":93},
  {"name":"Portuguese (Brazil) - português (Brasil)","code":"pt-BR","id":94},
  {"name":"Portuguese (Portugal) - português (Portugal)","code":"pt-PT","id":95},
  {"name":"Punjabi - ਪੰਜਾਬੀ","code":"pa","id":96},
  {"name":"Quechua","code":"qu","id":97},
  {"name":"Romanian - română","code":"ro","id":98},
  {"name":"Romanian (Moldova) - română (Moldova)","code":"mo","id":99},
  {"name":"Romansh - rumantsch","code":"rm","id":100},
  {"name":"Russian - русский","code":"ru","id":101},
  {"name":"Scottish Gaelic","code":"gd","id":102},
  {"name":"Serbian - српски","code":"sr","id":103},
  {"name":"Serbo - Croatian","code":"sh","id":104},
  {"name":"Shona - chiShona","code":"sn","id":105},
  {"name":"Sindhi","code":"sd","id":106},
  {"name":"Sinhala - සිංහල","code":"si","id":107},
  {"name":"Slovak - slovenčina","code":"sk","id":108},
  {"name":"Slovenian - slovenščina","code":"sl","id":109},
  {"name":"Somali - Soomaali","code":"so","id":110},
  {"name":"Southern Sotho","code":"st","id":111},
  {"name":"Spanish - español","code":"es","id":112},
  {"name":"Spanish (Argentina) - español (Argentina)","code":"es-AR","id":113},
  {"name":"Spanish (Latin America) - español (Latinoamérica)","code":"es-419","id":114},
  {"name":"Spanish (Mexico) - español (México)","code":"es-MX","id":115},
  {"name":"Spanish (Spain) - español (España)","code":"es-ES","id":116},
  {"name":"Spanish (United States) - español (Estados Unidos)","code":"es-US","id":117},
  {"name":"Sundanese","code":"su","id":118},
  {"name":"Swahili - Kiswahili","code":"sw","id":119},
  {"name":"Swedish - svenska","code":"sv","id":120},
  {"name":"Tajik - тоҷикӣ","code":"tg","id":121},
  {"name":"Tamil - தமிழ்","code":"ta","id":122},
  {"name":"Tatar","code":"tt","id":123},
  {"name":"Telugu - తెలుగు","code":"te","id":124},
  {"name":"Thai - ไทย","code":"th","id":125},
  {"name":"Tigrinya - ትግርኛ","code":"ti","id":126},
  {"name":"Tongan - lea fakatonga","code":"to","id":127},
  {"name":"Turkish - Türkçe","code":"tr","id":128},
  {"name":"Turkmen","code":"tk","id":129},
  {"name":"Twi","code":"tw","id":130},
  {"name":"Ukrainian - українська","code":"uk","id":131},
  {"name":"Urdu - اردو","code":"ur","id":132},
  {"name":"Uyghur","code":"ug","id":133},
  {"name":"Uzbek - o‘zbek","code":"uz","id":134},
  {"name":"Vietnamese - Tiếng Việt","code":"vi","id":135},
  {"name":"Walloon - wa","code":"wa","id":136},
  {"name":"Welsh - Cymraeg","code":"cy","id":137},
  {"name":"Western Frisian","code":"fy","id":138},
  {"name":"Xhosa","code":"xh","id":139},
  {"name":"Yiddish","code":"yi","id":140},
  {"name":"Yoruba - Èdè Yorùbá","code":"yo","id":141},
  {"name":"Zulu - isiZulu","code":"zu","id":142},
  {"name":"","code":"","id":143}
];